### ISSUE TITLE
Genesis Flow

### ISSUE THREAD

**Issue by avive** [spacemeshos/research#25]

**Comment by barakshani** [comment]
Eligibility and blocks

Upon changing the active set computation (https://github.com/spacemeshos/research/issues/2), we can proceed as follows:
1. Have an ATX0 (with the random hash taken from somewhere), which declares Genesis (layer 0 of epoch 0). In principal ATX0 gives eligibility to produce blocks in epoch 1, though we don't really need this property (e.g. there would be no transactions).
2. ATX0 is the Positioning ATX for all ATXs that would be published in epoch 1.
3. Blocks in epoch 2 declare the active set that they see by pointing specifically to all the (free-standing) ATXs. Note that we can also use ATX0 eligibility in epoch 1 to produce a block in the very last layer of epoch 1 that includes all the ATXs that were published during epoch 1, so the view becomes one block instead of a list of ATXs.

Hare bootstrap

There should be consensus about the eligible parties as well as the participation threshold for each round (and a beacon, which can be taken from ATX0).

One option is that, as explained above, ATX0 produces BLOCK0, at the last layer of epoch 1, that includes all the ATXs that were published during epoch 1. This BLOCK0 may be used for the Hare active set.
The downside of this suggestion is that the entire network would rely on a single entity to actually produce this block, and also this entity decides who may participate in that Hare

A second option is that in the first layers we look at all the blocks that are input to the Hare CP (in the preround messages) and consider only the ATXs that are referenced in the blocks. That is, once a preround message is received, we first go over the ATXs in it and check whether the sending party is eligible to participate by whether its ATX appears in one of the blocks (or appeared earlier).
In the first few layers we may not have all actual eligible parties (those that published an ATX) participating, but once there's an honest block generated, it will contain all orphaned ATXs and all tortoise-eligible parties will also be hare-eligible.
There are a few subtleties here. Note that in the current implementation we always receive preround messages, and that we may want to propagate all hare messages in the beginning. 

Another possibility is to allow everyone to participate in the Hare protocol until we achieve consensus on history (either tortoise’s p_base, or the first Hare results), but this mainly depends on how many unique nodes we expect to have in Genesis..
**

Note that ATX0 doesn't have to be an ATX, it may be just a hash.
