### ISSUE TITLE
Construct efficient ATX for variable PoST size commitments

### ISSUE THREAD

**Issue by avive** [spacemeshos/research#29]
Specify any other protocol components changes that need to happen to support variable post. @noamnelke

**Comment by avive** [comment]
This is the most important user-facing feature of Spacemes 0.2

**Comment by noamnelke** [comment]
Assuming we're talking about virtual IDs (that's what was discussed the last time I remember talking about the subject), this hardly affects the ATX flow in the node. The biggest changes required are in the block oracle and block eligibility validator, as well as the equivalent components of the hare.

Virtual IDs, as I understand it, means that instead of using a simple node ID, we'll now use a composite of node ID + virtual ID counter.

I think that we can easily make the protocol future-proof by including a virtual ID counter of 0 everywhere we use the node ID and rejecting any other value at first. Later we can release validation support for other values and once the the majority of nodes were upgraded to support the other counter values start supporting the virtual IDs.

**Comment by barakshani** [comment]
No further research needed
